import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:myliveevent/enumeration/msg_type.dart';
import 'package:myliveevent/model/event.dart';
import 'package:myliveevent/model/user.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'chat.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'chat.g.dart';

@freezed
abstract class Chat with _$Chat {
  const factory Chat({
    String? id,
    String? msg,
    MsgType? type,
    DateTime? time,
    User? sender,
    Event? event
  }) = _Chat;

  factory Chat.fromJson(Map<String, dynamic> json) => _$ChatFromJson(json);
// Map<String, dynamic> toJson() => toJson();
}