import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:myliveevent/model/user.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'event.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'event.g.dart';

@freezed
abstract class Event with _$Event {
  const factory Event({
    int? id,
    String? nom,
    String? description,
    String? channel,
    DateTime? date_debut,
    DateTime? date_fin,
    bool? live,
    int? vue_max,
    int? vue_en_cours,
    Map<String, dynamic>? position,
    String? organisateur //email organisateur
  }) = _Event;

  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);
// Map<String, dynamic> toJson() => toJson();
}
