// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbA2JfMOX4ZgE99en7NPEP0Iw_XZeBCxI',
    appId: '1:342430231109:android:0c08b8590a34607f2e512c',
    messagingSenderId: '342430231109',
    projectId: 'event-be232',
    storageBucket: 'event-be232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbczoJp1r7eiJoBzgD2A5vtkeDCmO9G4I',
    appId: '1:342430231109:ios:037c065903f015cb2e512c',
    messagingSenderId: '342430231109',
    projectId: 'event-be232',
    storageBucket: 'event-be232.appspot.com',
    iosClientId: '342430231109-fpvafuq1edvjji2fusdc221cpocbamgi.apps.googleusercontent.com',
    iosBundleId: 'com.myliveevent.myliveevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbczoJp1r7eiJoBzgD2A5vtkeDCmO9G4I',
    appId: '1:342430231109:ios:037c065903f015cb2e512c',
    messagingSenderId: '342430231109',
    projectId: 'event-be232',
    storageBucket: 'event-be232.appspot.com',
    iosClientId: '342430231109-fpvafuq1edvjji2fusdc221cpocbamgi.apps.googleusercontent.com',
    iosBundleId: 'com.myliveevent.myliveevent',
  );
}
